
const ITEM_LIST = [
    {item_no:0, src: 'p_img1.jpg', state:'LIMITED EDITION', title:' 스터드 프린지 와이드 벨트', price: 129900, desc: '면 방적 소재로 제작된 프록 코트 스타일의 코트. 라운드 네크라인과 긴소매 디자인. 앞면 포켓. 같은 소재의 끈으로 허리 조절 가능. 밑단 절개 가공. 앞면 메탈 후크 여밈.'}, 
    {item_no:1, src: 'p_img2.jpg', state:'LIMITED EDITION', title:'프린트 원피스' , price: 279900, desc: '비스코스 방적 소재 원피스. A라인으로 마감된 긴소매 라운드넥 디자인. 같은 소재의 리본 매듭으로 조절 가능한 벨트. 메탈 액세서리 디테일. 얇은 플리츠 소재. 언밸런스 밑단.'}, 
    {item_no:2, src: 'p_img3.jpg', state:'LIMITED EDITION', title:'포플린 자수 원피스' , price: 189900, desc: '면 방적 소재 원피스. 라운드 네크라인과 커프스 마감 긴소매 디자인. 옆면 심라인 히든 포켓. 톤온톤 펀칭 자수 디테일. 동일 소재의 리본 매듭으로 조절 가능한 벨트.'}, 
    {item_no:3, src: 'p_img4.jpg', state:'LIMITED EDITION', title:'절개 롱 원피스' , price: 189900, desc: '비스코스 방적 소재로 제작된 롱 원피스. 라운드넥 브이넥 디자인과 긴소매. 심라인 히든 포켓. 동일 소재의 리본 매듭 조절 가능 벨트. 메탈 소재 파이핑 디테일. 밑단 절개 가공. 앞면 메탈 후크 여밈.'}, 
    {item_no:4, src: 'p_img5.jpg', state:'LIMITED EDITION', title:'비즈 쇼트 원피스' , price: 189900, desc: '끈으로 조절 가능한 케이프 스타일 소매의 브이넥 쇼트 원피스. 앞면 비즈 아플리케 디테일. 드레이프 소재와 와이드 벨트 스타일의 동일 소재 오버레이. 앞면 하단 절개 가공.'}, 
    {item_no:5, src: 'p_img6.jpg', state:'LIMITED EDITION', title:'롱 네크리스' , price: 55900, desc:'견고한 체인과 메탈 비즈 장식이 있는 목걸이. 카라비너를 사용한 조절 가능한 잠금.'},
    {item_no:6, src: 'p_img7.jpg', state:'LIMITED EDITION', title:'링 세트' , price: 49900, desc:'비즈 아플리케가 매치된 롱 드롭 이어링. 클러치로 고정.'},
    {item_no:7, src: 'p_img8.jpg', state:'LIMITED EDITION', title:'넥타이 네크리스' , price: 109900, desc:'메탈 체인 아플리케가 있는 넥타이 스타일 네크리스..'},
    {item_no:8, src: 'p_img9.jpg', state:'LIMITED EDITION', title:'스웨이드 프린지 가죽 케이스프' , price: 329900, desc:'100% 스웨이드 가죽 소재 케이프. 라운드넥. 같은 소재 프린지 가공 언밸런스 밑단.'},
    {item_no:9, src: 'p_img10.jpg', state:'LIMITED EDITION', title:'프린트 원피스' , price: 189900, desc:'브이넥 슬리브리스 미디 원피스. 배색 플라워 스탬핑 디테일. 내부 안감.'},
    {item_no:10, src: 'p_img11.jpg', state:'LIMITED EDITION', title:'리미티드 에디션 프린트 미니 원피스' , price: 209900, desc:'케이프 스타일 소매의 브이넥 미니 원피스. 메탈 액세서리와 뒷면 절개 디테일. 앞면 버튼 여밈.'},
    {item_no:11, src: 'p_img12.jpg', state:'LIMITED EDITION', title:'리미티드 에디션 자수 트라이앵글 브라렛' , price: 109900, desc:'길이 조절 가능한 얇은 멜빵이 달린 트라이앵글 브라렛. 비즈 장식 자수 디테일. 뒷면의 메탈 후크 여밈.'},
    {item_no:12, src: 'p_img13.jpg', state:'LIMITED EDITION', title:'애니멀 프린트 코튼 맥시 백' , price: 49900, desc:''},
    {item_no:13, src: 'p_img14.jpg', state:'LIMITED EDITION', title:'콤비 원피스' , price: 189900, desc:'비스코스 방적 소재로 제작된 미디 원피스. 브이넥 슬리브리스 디자인. 배색 소재와 컷아웃 디테일. 앞면 버튼으로 여밈.'},
    {item_no:14, src: 'p_img15.jpg', state:'LIMITED EDITION', title:'롱 이어링' , price: 45900, desc:'비즈 아플리케가 매치된 롱 드롭 이어링. 클러치로 고정.'},
    {item_no:15, src: 'p_img16.jpg', state:'LIMITED EDITION', title:'스터드 가죽 와이드 벨트' , price: 109900, desc:'100% 가죽 소재의 와이드 벨트. 스터드 장식 디테일. 같은 소재의 끈으로 여미고 리본 매듭으로 조절 가능.'},
    {item_no:16, src: 'p_img17.jpg', state:'LIMITED EDITION', title:'프릴 스커트' , price: 129900, desc:'하이웨이스트 미니 스커트. 배색 소재로 제작된 풍성한 프릴 밑단. 옆면 심라인 콘실 지퍼 여밈.'},
    {item_no:17, src: 'p_img18.jpg', state:'LIMITED EDITION', title:'롱 이어링' , price: 45900, desc:'비즈 아플리케가 매치된 롱 드롭 이어링. 클러치로 고정.'},
    {item_no:18, src: 'p_img19.jpg', state:'LIMITED EDITION', title:'숏 재킷' , price: 209900, desc:'비스코스와 리넨 혼방 방적 소재로 제작된 쇼트 재킷. 플랩오버 칼라와 긴소매 디자인. 같은 색상의 소재 배색 디테일. 언밸런스 밑단. 같은 색상의 드로스트링으로 앞면 여밈.'},
    {item_no:19, src: 'p_img20.jpg', state:'LIMITED EDITION', title:'체인 네크리스' , price: 55900, desc:'견고한 체인과 메탈 비즈 장식이 있는 목걸이. 카라비너를 사용한 조절 가능한 잠금.'},
    {item_no:20, src: 'p_img21.jpg', state:'LIMITED EDITION', title:'측면 디테일 팬츠' , price: 169900, desc:'100% 면 방적 소재 팬츠. 미드라이즈 및 버클 허리 디자인. 앞면과 뒷면 포켓. 같은 소재의 측면 디테일. 앞면 지퍼와 메탈 후크 여밈.'},
    {item_no:21, src: 'p_img22.jpg', state:'', title:'레이스 프릴 브라우스' , price: 59900, desc:'브이넥 라운드넥 긴소매 블라우스. 프릴과 레이스 가공 디테일. 앞면 톤온톤 버튼 여밈.'},
    {item_no:22, src: 'p_img23.jpg', state:'', title:'비닐 힐 샌들' , price: 59900, desc:'샌들 스타일의 힐 슈즈. 뮬 스타일. 비닐 스트랩. 소프트 효과 밑창. 얇은 하이힐. 스퀘어 토 마감.'},
    {item_no:23, src: 'p_img24.jpg', state:'Z1975', title:'롱 데님 원피스' , price: 45900, desc:'라펠 칼라 긴소매 원피스. 앞면 포켓과 뒷면 패치 포켓. 앞면 절개 밑단. 앞면 메탈 버튼으로 여밈.'},
    {item_no:24, src: 'p_img25.jpg', state:'ZW COLLECTION', title:'벌룬 팬츠' , price: 189900, desc:'면 혼방 및 실크 26% 소재 방적 원단으로 제작된 미드라이즈 팬츠. 짧은 내피 안감. 엘라스틱 소재 가공 벌룬 밑단. 스티치 안쪽으로 숨겨진 지퍼 여밈.'},
    {item_no:25, src: 'p_img26.jpg', state:'ZW COLLECTION', title:'컬렉션 지퍼 미디 원피스' , price: 109900, desc:'면 방적 소재로 제작된 미디 원피스. V넥과 넓은 멜빵 디자인. A라인 가공 밑단. 앞면 금속 지퍼 여밈.'},
    {item_no:26, src: 'p_img27.jpg', state:'', title:'케이블 니트 자켓' , price: 79900, desc:'라운드넥 긴소매 재킷. 앞면 플래킷 포켓. 앞면 버튼 여밈.'},
    {item_no:27, src: 'p_img28.jpg', state:'LIMITED EDITION', title:'스웨이드 프린지 미니 시티백' , price: 299900, desc:'스웨이드 소재 미니 시티백 스타일 가방. 탑 부분 스터드와 프린지 디테일. 지퍼로 여미는 내부 포켓. 견고한 메탈 소재 손잡이와 길이 조절이 가능한 크로스백 스타일 스트랩.'},
    {item_no:28, src: 'p_img29.jpg', state:'', title:'자수 트라이앵글 브라렛' , price: 109900, desc:'조절 가능한 가느다란 어깨끈이 달린 트라이앵글 브라렛. 비즈 아플리케가 매치된 자수 장식 디테일. 뒷면에서 메탈 후크로 여밈.'},
    {item_no:29, src: 'p_img30.jpg', state:'', title:'프릴 디테일 도티드 스위스 블라우스' , price: 57900, desc:'끈과 프릴이 있는 라운드넥 세미 시스루 블라우스. 엘라스틱 소재와 프릴로 마감된 긴소매. 앞면 버튼 여밈.'},
    {item_no:30, src: 'p_img31.jpg', state:'LIMITED EDITION', title:'스터드 기모노' , price: 169900, desc:'비스코스 방적 소재의 세미 시스루 기모노. 절개 디테일의 케이프 소매. 스티치 안쪽으로 숨겨진 옆면 포켓. 톤온톤 프린지 디테일. 리본 매듭으로 조절 가능한 허리끈. 언밸런스 밑단.'},
    {item_no:31, src: 'p_img32.jpg', state:'LIMITED EDITION', title:'프린트 미디 스커트' , price: 169900, desc:'비스코스 방적 소재로 제작된 하이웨이스트 미디 스커트. 메탈 소재 파이핑 디테일. 절개 가공 밑단. 메탈 후크와 같은 소재의 리본 매듭으로 앞면 여밈.'},
    {item_no:32, src: 'p_img33.jpg', state:'LIMITED EDITION', title:'미니 큐브 백' , price: 59900, desc:'큐브 모양 가방. 손잡이와 탈부착 및 길이 조절이 가능한 크로스백 손잡이. 내부 카드지갑 포켓. 배색 아플리케와 지퍼 손잡이로 여밈.'},
    {item_no:33, src: 'p_img34.jpg', state:'LIMITED EDITION', title:'스터드 스웨이드 미니 시티백' , price: 259900, desc:'스웨이드 소재 미니 시티백 스타일 가방. 탑 부분 스터드와 프린지 디테일. 지퍼로 여미는 내부 포켓. 견고한 메탈 소재 손잡이와 길이 조절이 가능한 크로스백 스타일 스트랩.'},
    {item_no:34, src: 'p_img35.jpg', state:'LIMITED EDITION', title:'페이크 레더 쇼트 트렌치 코트' , price: 109900, desc:'버클 커프스 마감 긴소매 라펠 칼라의 쇼트 트렌치 코트. 옆면 포켓. 배색 안감. 같은 소재의 벨트. 앞면 버튼 여밈.'},
    {item_no:35, src: 'p_img36.jpg', state:'', title:'스웨이드 플랫폼 웨지' , price: 109900, desc:'스웨이드 소재의 플랫폼 웨지 슈즈. 앞부분 와이드 스트랩. 플랫폼 솔. 스퀘어 토 마감.'},
    {item_no:36, src: 'p_img37.jpg', state:'LIMITED EDITION', title:'스티치 미니 원피스' , price: 79900, desc:'레이스 트리밍과 엘라스틱 소재로 마감된 긴소매의 라운드넥 원피스. 앞면 스티치 디테일. 앞면 버튼 여밈.'},
    {item_no:37, src: 'p_img38.jpg', state:'ZW COLLECTION', title:'벌룬 봄버 자켓' , price: 149900, desc:'라이오셀 방적 소재로 제작된 봄버 재킷. 플랩오버 칼라와 벌룬 긴소매 디자인. 벌룬 턱 디테일 밑단. 앞면 지퍼 여밈.'},
    {item_no:38, src: 'p_img39.jpg', state:'LIMITED EDITION', title:'파인 코튼 탑' , price: 39900, desc:'면 방적 소재 탑. 라운드넥 슬리브리스 디자인. 골지 니트 소재'},
    {item_no:39, src: 'p_img40.jpg', state:'LIMITED EDITION', title:'100% 스웨이드 프린지 가죽' , price: 369900, desc:'100% 스웨이드 가죽 소재의 하이웨이스트 팬츠. 톤온톤 옆면 프린지 디테일. 스티치리스 A라인 밑단 가공. 앞면 지퍼, 버튼, 메탈 후크 여밈.'},
    {item_no:40, src: 'p_img41.jpg', state:'', title:'비즈 크로셰 발레리나 슈즈' , price: 59900, desc:'크로셰 소재 발레리나 스타일 슈즈. 앞면 스트랩과 비즈 디테일. 앵클 스트랩으로 여밈. 라운드 엔드 마감.'},
    {item_no:41, src: 'p_img42.jpg', state:'', title:'하이힐 스터드 샌들' , price: 89900, desc:'가죽 샌들 스타일 슈즈. 전면 메탈 스터드 디테일. 와이드 하이 힐. 발목의 앵클 스트랩에 조절 가능한 버클로 여밈. 스퀘어 토 마감.'},
    {item_no:42, src: 'p_img43.jpg', state:'', title:'레이스 콤비 블라우스' , price: 59900, desc:'하이넥 긴소매 블라우스. 톤온톤 레이스 트리밍 디테일과 프릴 마감 밑단. 히든 버튼으로 여미는 뒷면 절개.'},
    {item_no:43, src: 'p_img44.jpg', state:'', title:'스터드 레더 플랫 샌들' , price: 109900, desc:'가죽 플랫 샌들 스타일 슈즈. 발가락 고정. 전면부에 메탈릭 스터드와 심라인 톱스티칭 디테일이 있는 와이드 스트랩. 라운드 엔드 마감.'},
    {item_no:44, src: 'p_img45.jpg', state:'LIMITED EDITION', title:'파인 코튼 탑' , price: 39900, desc:'면 방적 소재 탑. 라운드넥 슬리브리스 디자인. 골지 니트 소재.'},
    {item_no:45, src: 'p_img46.jpg', state:'ZW COLLECTION', title:'스트라이프 언밸런스 스커트' , price: 129900, desc:'미드라이즈 미디 스커트. 배색 스트라이프 스탬핑 디테일. 언밸런스한 밑단. 리본 매듭으로 조절 가능한 앞면 파레오 스타일 여밈.'},
    {item_no:46, src: 'p_img47.jpg', state:'LIMITED EDITION', title:'워싱 텍스트 티셔츠' , price: 19900, desc:'워싱 처리된 100% 면 소재 티셔츠. 라운드넥 반소매 디자인. 배색 텍스트 디테일.'},
    {item_no:47, src: 'p_img48.jpg', state:'LIMITED EDITION', title:'코튼 티셔츠' , price: 45900, desc:'100% 면 방적 소재로 제작된 티셔츠. 라운드넥 긴소매 디자인.'},
    {item_no:48, src: 'p_img49.jpg', state:'LIMITED EDITION', title:'스터드 가죽 와이드 벨트' , price: 109900, desc:'100% 가죽 소재의 와이드 벨트. 스터드 장식 디테일. 같은 소재의 끈으로 여미고 리본 매듭으로 조절 가능.'},
    {item_no:49, src: 'p_img50.jpg', state:'', title:'롤업 멜빵 티셔츠' , price: 21900, desc:'면 혼방 소재 티셔츠. 라운드넥과 멜빵 디자인. 롤업 티셔츠 효과.'}]





